### ISSUE TITLE
Some issues setting up a ceremony on Gesell

### ISSUE THREAD

**Issue by sacha-l** [encointer/encointer-node#272]
Setup:
* I'd suggest to give another option for developer to build the client from source:
1. git clone https://github.com/encointer/encointer-node.git
2. cargo build --release
3. chmod +x target/release/encointer-client-notee
4. NURL=wss://gesell.encointer.org && NPORT=443
5. alias nctr-gsl="./target/release/encointer-client-notee -u $NURL -p $NPORT"
 
Funding:
* Alice account for Gesell: if I were to use Polkadot JS Apps UI, what instructions am I missing to fund an account?
* Trying to fund an account using `encointer-client-notee` client and getting the following insufficient funds error: `[2022-11-24T16:03:24Z ERROR encointer_client_notee::utils] insufficient funds: fee: 86298000 ed: 500 bal: 81699625`

**Comment by brenzi** [comment]
Faucet has been topped up, so the funding issues should be solved for now

**Comment by brenzi** [comment]
on the building instructions: sure, that could be a good thing to add and it can be easily skipped

**Comment by sacha-l** [comment]
Cool. Yes the faucet was dry, now its fixed thanks. 

For instructions, I can make a PR to add. Other issues that came up:

* It would be nice to have instructions on, when registering a community how to use an existing account or clarify that using the cli tool with `new-account` is just best practice. Right now I get `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPhrase', client/src/utils.rs:230:83` even following the keystore file creation pattern, not sure why.
* Instructions missing for addinf community metadata. I get the error: `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CommunityMetadataError::InvalidAmountCharactersInSymbol(4)', client/src/community_spec.rs:127:21` which I understand why now, but we could also add this to clarify in the docs. In case, the symbol length was one character too long.
