### ISSUE TITLE
[teeproxy] node hot upgrade to 0.3.7-tee fails (Storage root must match that calculated)

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#44]
the upgrade from 2.0.0 to master seems to be a breaking change! The onchain wasm upgrade worked, but when restarting with the new node release, I get:

```
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:Encointer Node TEE proxy
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:✌️  version 0.3.7-2c8b506-x86_64-linux-gnu
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:❤️  by encointer.org <alain@encointer.org>, 2017-2020
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:📋 Chain specification: Encointer Testnet Cantillon
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:🏷 Node name: cantillon-api
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:👤 Role: FULL
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:💾 Database: RocksDb at /home/cantillon/.local/share/encointer-node-teeproxy-0.3.7/chains/nctr-cln/db
Dec 10 10:29:02 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:02.861   INFO main sc_cli::runner:⛓  Native runtime: encointer-node-teeproxy-5 (encointer-node-teeproxy-0.tx1.au0)
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.175   INFO main sc_service::client::client:🔨 Initializing Genesis block/state (state: 0x0929…cf9d, header-hash: 0x2b67…470f)
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.179   INFO main afg:👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.230   INFO main sc_consensus_slots:⏱  Loaded block-time = 6000 milliseconds from genesis on first-launch
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.231   INFO main sub-libp2p:🏷 Local node identity is: 12D3KooWFVkwqfUyounbgE3L81sepigkR47a2NvNGhm7yNvbNrtw
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.234   INFO main sc_service::builder:📦 Highest known block at #0
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.234   INFO tokio-runtime-worker substrate_prometheus_endpoint::known_os:〽️ Prometheus server started at 127.0.0.1:9615
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.236   INFO                 main parity_ws:Listening for new connections on 127.0.0.1:9944.
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: 2020-12-10 10:29:05.449   INFO tokio-runtime-worker encointer:next phase change at: 1605024600000
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: Hash: given=b0d7477cdd2f17d1737ed3649a1183683f91cfea4f77a4846eb802d3baf4268d, expected=721441db1191e6c6c56e5a18699c5b4ceff19d9b627653d4284c06ea45bc8318
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: ====================
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: Version: 0.3.7-2c8b506-x86_64-linux-gnu
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    0: sp_panic_handler::set::{{closure}}
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    1: std::panicking::rust_panic_with_hook
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:              at rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:581:17
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    2: std::panicking::begin_panic::{{closure}}
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    4: std::panicking::begin_panic
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::final_checks
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    6: tracing::span::Span::in_scope
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    8: <encointer_node_teeproxy_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::>
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:    9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   10: std::thread::local::LocalKey<T>::with
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   19: sp_api::Core::execute_block_with_context
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   20: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   21: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   22: <sc_consensus_aura::AuraBlockImport<Block,C,I,P> as sp_consensus::block_import::BlockImport<Block>>::import_block
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   23: sp_consensus::import_queue::import_single_block_metered
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   26: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   27: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   32: std::thread::local::LocalKey<T>::with
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   33: futures_executor::local_pool::block_on
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   34: tokio::runtime::task::core::Core<T,S>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   36: tokio::runtime::task::harness::Harness<T,S>::poll
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   37: tokio::runtime::blocking::pool::Inner::run
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   38: tokio::runtime::context::enter
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   39: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   40: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:              at rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/alloc/src/boxed.rs:1042:9
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:              at rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/alloc/src/boxed.rs:1042:9
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:       std::sys::unix::thread::Thread::new::thread_start
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:              at rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys/unix/thread.rs:89:17
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   42: start_thread
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:   43: clone
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/abrenzikofer/.cargo/git/checkouts/substrate-7e08433d4c370a21/a208da1/frame/execut>
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: This is a bug. Please report it at:
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]:         support.anonymous.an
Dec 10 10:29:05 cantillon-api encointer-node-teeproxy[220265]: Hash: given=84815e1441a8eca9db35e4228f355040e72b1437986dfde7a041f5d02f62b0d3, expected=9b225edb9eea23bac8ad28de84285cce43adbc012edac84ee52e25a108efc8b3

```

**Comment by brenzi** [comment]
According to @bkchr this may caused by not updating the spec version

**Comment by brenzi** [comment]
yes it was
